module.exports = {
  prefix: 'tw-',
  important: true,
  separator: ':',
  shadowLookup: true,
  theme: {
    colors: {
      transparent: 'transparent',

      black: '#323b4b',
      'grey-darkest': '#333c4a',
      'grey-darker': '#979797',
      'grey-dark': '#8795a1',
      'grey': '#d3d2ce',
      'grey-light': '#dae1e7',
      'grey-lighter': '#f1f5f8',
      'grey-lightest': '#f8fafc',
      white: '#ffffff',

      'red-darkest': '#710e0b',
      'red-darker': '#911e1a',
      'red-dark': '#ac2925',
      red: '#c9302c',
      'red-light': '#d64440',
      'red-lighter': '#d9534f',
      'red-lightest': '#ffb4b4',

      'orange-dark': '#d36408',
      orange: '#f0750f',
      'orange-light': '#f89406',
      'orange-lighter': '#f39c12',
      'orange-lightest': '#f0ad4e',

      'green-darkest': '#265228',
      'green-darker': '#2b542c',
      'green-dark': '#4ca54c',
      green: '#5cb85c',
      'green-light': '#7acc7a',
      'green-lighter': '#93de93',
      'green-lightest': '#def7de',
      'green-pct-header': '#adba00',

      'aqua-dark': '#32917d',
      aqua: '#45b39c',

      'blue-darkest': '#204d74',
      'blue-darker': '#286090',
      'blue-dark': '#3581c4',
      blue: '#659cc6',
      'blue-light': '#65b3e7',
      'blue-lighter': '#87c7e5',
      'blue-lightest': '#c4e3f3',

      purple: '#8a00ff',

      'pink-darker': '#a94442',
      'pink-dark': '#d9534f',
      'pink': '#d99e88',
      'pink-light': '#e4b9b9',
      'pink-lighter': '#ebcccc',
      'pink-lightest': '#f2dede',

      'yellow-dark': '#ddb91f',
      'yellow': '#f2bd31',
    },

    screens: {
      sm: '576px',
      md: '768px',
      lg: '992px',
      xl: '1200px',
    },

    fontFamily: {
      heading: [
        'Lato',
        'Helvetica Neue',
        'sans-serif',
      ],
      sans: [
        'Source Sans Pro',
        'system-ui',
        'BlinkMacSystemFont',
        '-apple-system',
        'Segoe UI',
        'Roboto',
        'Oxygen',
        'Ubuntu',
        'Cantarell',
        'Fira Sans',
        'Droid Sans',
        'Helvetica Neue',
        'sans-serif',
      ],
      serif: [
        'Roboto Slab',
        'Constantia',
        'Lucida Bright',
        'Lucidabright',
        'Lucida Serif',
        'Lucida',
        'DejaVu Serif',
        'Bitstream Vera Serif',
        'Liberation Serif',
        'Georgia',
        'serif',
      ],
      mono: [
        'Menlo',
        'Monaco',
        'Consolas',
        'Liberation Mono',
        'Courier New',
        'monospace',
      ],
    },

    fontSize: {
      xs: '.75rem',
      sm: '.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '4rem',
      '7xl': '5rem',
      '8xl': '6rem',
      '10xl': '8rem',
      '12xl': '10rem',
      '14xl': '12rem',
      '16xl': '14rem',
      '18xl': '16rem',
      '20xl': '18rem',
      '22xl': '20rem',
    },

    borderColor: theme => ({
      default: theme('colors.grey-light'),
      ...theme('colors'),
    }),

    height: theme => ({
      auto: 'auto',
      ...theme('spacing'),
      full: '100%',
      screen: '100vh',
      '80': '20rem',
      '96': '24rem',
      '120': '30rem',
      '128': '36rem',
      '160': '40rem',
      '200': '50rem',
      '224': '56rem',
    }),

    maxWidth: {
      xs: '20rem',
      sm: '30rem',
      md: '40rem',
      lg: '50rem',
      xl: '60rem',
      '2xl': '70rem',
      '3xl': '80rem',
      '4xl': '90rem',
      '5xl': '100rem',
      full: '100%',
    },

    zIndex: {
      auto: 'auto',
      '0': 0,
      '1': 1,
      '10': 10,
      '20': 20,
      '30': 30,
      '40': 40,
      '50': 50,
    },

    container: {
      center: true,
      padding: '1rem',
    },

    extend: {
      minHeight: {
        '350': '350px',
      },
      inset: {
        50: '50px',
      },
      margin: {
        '72': '20rem',
        '74': '24rem',
        '76': '28rem',
        '78': '32rem',
        '86': '40rem',
        '94': '48rem',
        '102': '56rem',
        '110': '64rem',

        '-72': '-20rem',
        '-74': '-24rem',
        '-76': '-28rem',
        '-78': '-32rem',
        '-86': '-40rem',
        '-90': '-45rem',
        '-94': '-48rem',
        '-102': '-56rem',
        '-110': '-64rem',
      },
    },
  },
  variants: {
    appearance: ['responsive'],
    backgroundAttachment: ['responsive'],
    backgroundColor: ['responsive', 'hover', 'focus'],
    backgroundPosition: ['responsive'],
    backgroundRepeat: ['responsive'],
    backgroundSize: ['responsive'],
    borderCollapse: [],
    borderColor: ['responsive', 'hover', 'focus'],
    borderRadius: ['responsive'],
    borderStyle: ['responsive', 'hover', 'focus'],
    borderWidth: ['responsive'],
    cursor: ['responsive'],
    display: ['responsive', 'hover', 'focus'],
    flexDirection: ['responsive'],
    flexWrap: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: ['responsive'],
    justifyContent: ['responsive'],
    alignContent: ['responsive'],
    flex: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    float: ['responsive'],
    fontFamily: ['responsive'],
    fontWeight: ['responsive', 'hover', 'focus'],
    height: ['responsive'],
    lineHeight: ['responsive'],
    listStylePosition: ['responsive'],
    listStyleType: ['responsive'],
    margin: ['responsive'],
    maxHeight: ['responsive'],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: ['responsive'],
    negativeMargin: ['responsive'],
    objectFit: ['responsive'],
    objectPosition: ['responsive'],
    opacity: ['responsive', 'hover', 'focus'],
    outline: ['focus'],
    overflow: ['responsive'],
    padding: ['responsive'],
    pointerEvents: ['responsive'],
    position: ['responsive'],
    inset: ['responsive'],
    resize: ['responsive'],
    boxShadow: ['responsive', 'hover', 'focus'],
    fill: [],
    stroke: [],
    tableLayout: ['responsive'],
    textAlign: ['responsive'],
    textColor: ['responsive', 'hover', 'focus'],
    fontSize: ['responsive', 'hover', 'focus'],
    fontStyle: ['responsive', 'hover', 'focus'],
    textTransform: ['responsive', 'hover', 'focus'],
    textDecoration: ['responsive', 'hover', 'focus'],
    fontSmoothing: ['responsive'],
    letterSpacing: ['responsive'],
    userSelect: ['responsive'],
    verticalAlign: ['responsive'],
    visibility: ['responsive'],
    whitespace: ['responsive'],
    wordBreak: ['responsive'],
    width: ['responsive'],
    zIndex: ['responsive'],
  },
};